<<<<<<< HEAD
name: Test Pipeline Migration

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
=======
name: TEST - Manual Approval for Migration (Environment)

on:
  workflow_dispatch:

jobs:
  deploy-simulated:
    name: Deploy (simulado)
>>>>>>> 4fa67879051e8c36d090d87599c2e377a8acd379
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "🔧 Rodando build..."
          sleep 3

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: |
          echo "🚀 Rodando deploy..."
          sleep 3 
  migrate:
    runs-on: ubuntu-latest
    needs: deploy
    if: contains(github.event.pull_request.title, '[run-migration]')

    steps:
      - name: Run Migration
        run: |
          echo "🗄️ Rodando migration..."
          sleep 5




#name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

#on: 
  #push:
    #branches:
      #- 'main'

#jobs:
  #Explore-GitHub-Actions:
    #runs-on: ubuntu-latest
    #steps:
      #- name: Check out repository code
      #  uses: actions/checkout@v4
      #- run: ./script.sh ${{ github.ref_name }}
      #- run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      #- run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      #- run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
     # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      #- name: List files in the repository
      #  run: |
       #   ls ${{ github.workspace }}
    #  - run: echo "🍏 This job's status is ${{ job.status }}."

 # My-New-Job:
    #runs-on: ubuntu-latest
    #needs: Explore-GitHub-Actions
   # steps:
   #   - run: echo "Executing my new job with my steps"

=======
      - name: Deploy simulation
        run: |
          echo "✅ Deploy simulado iniciando..."
          sleep 8
          echo "✅ Deploy simulado finalizado."

  migration-simulated:
    name: Migration (simulado) - requer aprovação
    needs: deploy-simulated
    runs-on: ubuntu-latest
    environment: migration-test
    steps:
      - name: Migration simulation
        run: |
          echo "🚀 Migration simulado iniciando... teste"
          sleep 8
          echo "✅ Migration simulado finalizado."
>>>>>>> 4fa67879051e8c36d090d87599c2e377a8acd379
